version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/deploy/fusion/web:/home/deploy/fusion/web
    restart: always
    ports:
      - "0.0.0.0:443:443"
      # - "0.0.0.0:8089:8089"
