version: "3"

services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - /etc/letsencrypt/archive/fusion.minelytics.in:/opt/certs
